### ISSUE TITLE
Do not save rpivate keys

### ISSUE THREAD

**Issue by ljgarcia** [BioSchemas/bioschemas-map2model#17]
I hope the private keys and credentials at https://github.com/BioSchemas/Templates/blob/master/bsch2model/sdo-bioschemas-client.json are not real. If so, please remove and just add some comment to the file so people using the project will know they have provide their credentials there.

**Comment by guicalman** [comment]
Deleted sdo-bioschemas-client.json, added to .gitignore, each user should have to create his own file using a Google Account.
