### ISSUE TITLE
Move file name to configuration or parameters

### ISSUE THREAD

**Issue by ljgarcia** [BioSchemas/bioschemas-map2model#18]
You have a good start here https://github.com/BioSchemas/Templates/blob/master/bsch2model/read_spreadsheet.py. 
For later, move the file name to a parameter or configuration. Think a bit about how you want to take this to a production level, so people do not have to modify the code but just using it (unless something really needs to be changed, of course).

**Comment by guicalman** [comment]
Created configutarion.yml file.
